apiVersion: v1
kind: Pod
metadata:
  name: blue-deployment-pod
  labels: 
    deployment: blue
spec:
  containers:
    - name: tutum-hello-world-container
      image: tutum/hello-world
      ports:
        - containerPort: 80
  nodeName: ip-172-31-36-224
