apiVersion: v1
kind: Pod
metadata:
  name: green-deployment-pod
  labels: 
    deployment: green
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: deployment
                operator: In
                values:
                - blue
          topologyKey: kubernetes.io/hostname
  containers:
    - name: tutum-hello-world-container
      image: tutum/hello-world
      ports:
        - containerPort: 80
