apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
  selector:
    component: elasticsearch
