apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging-v1
  labels:
    k8s-app: kibana-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana:6.5.4
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
          - name: XPACK_SECURITY_ENABLED
            value: "true"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
